# Generated by Django 5.0.3 on 2026-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
