# Generated by Django 5.0.3 on 2026-04-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_quotationtemplate_description_subscription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentterm'),
        ),
    ]
