# Generated by Django 5.0.3 on 2026-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_quotationtemplate_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
