# Generated by Django 5.0.3 on 2026-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_cycle_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
