# Generated by Django 5.0.3 on 2026-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
